require('dotenv').config({ path: '.env.local' });
require('dotenv').config({ path: '.env' });

const axios = require('axios');
const { createClient } = require('@supabase/supabase-js');

// Configuration
const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL;
const SUPABASE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
const APOLLO_API_KEY = process.env.APOLLO_API_KEY;

if (!SUPABASE_URL || !SUPABASE_KEY) {
    console.error("❌ Missing Supabase credentials in .env");
    process.exit(1);
}

const supabase = createClient(SUPABASE_URL, SUPABASE_KEY);

async function generateApolloLeads() {
    console.log("🚀 STARTING APOLLO.IO B2B LEAD GENERATOR 🚀");

    if (!APOLLO_API_KEY) {
        console.log("⚠️ Apollo API Key not found in .env file.");
        console.log("⚠️ Injecting 5 high-quality AI-generated mock SaaS founders for demonstration...");
        
        const mockLeads = [
            { full_name: "Alex Hormozi", email: "alex@acquisition.com", company: "Acquisition.com", score: 95 },
            { full_name: "Sam Altman", email: "sam@openai.com", company: "OpenAI", score: 98 },
            { full_name: "Guillermo Rauch", email: "rauchg@vercel.com", company: "Vercel", score: 90 },
            { full_name: "Jason Lemkin", email: "jason@saastr.com", company: "SaaStr", score: 85 },
            { full_name: "Mathilde Collin", email: "mathilde@frontapp.com", company: "Front", score: 88 }
        ];

        let count = 0;
        for (const lead of mockLeads) {
            const { data: existing } = await supabase.from('leads').select('id').eq('email', lead.email).single();
            if (!existing) {
                await supabase.from('leads').insert([{
                    ...lead,
                    source: 'ai_assessment',
                    status: 'new',
                    notes: 'Demonstration lead generated by AI.'
                }]);
                console.log(`✅ Added ${lead.full_name} (${lead.company})`);
                count++;
            }
        }
        console.log(`\n🎉 Injected ${count} demonstration leads!`);
        console.log(`\n💡 To get 10,000+ REAL verified emails, add APOLLO_API_KEY to your .env file!`);
        return;
    }

    console.log("✅ Authenticated with Apollo.io. Searching for US-based SaaS Founders...");

    try {
        // Search Apollo for CEOs/Founders of Software companies
        const response = await axios.post('https://api.apollo.io/v1/mixed_people/search', {
            api_key: APOLLO_API_KEY,
            q_keywords: "SaaS",
            person_titles: ["Founder", "CEO"],
            organization_num_employees_ranges: ["1,10", "11,50"],
            page: 1,
            per_page: 25 // Change this to pull up to 100 at a time
        });

        const people = response.data.contacts || response.data.people || [];
        console.log(`✅ Found ${people.length} real leads from Apollo!`);

        let addedCount = 0;
        for (const person of people) {
            if (!person.email) continue; // Only want verified emails

            const newLead = {
                full_name: `${person.first_name} ${person.last_name}`,
                email: person.email,
                company: person.organization?.name || 'Independent',
                source: 'manual',
                status: 'new',
                notes: `Auto-generated via Apollo.io\nTitle: ${person.title}\nLinkedIn: ${person.linkedin_url}`,
                score: 80
            };

            const { data: existing } = await supabase.from('leads').select('id').eq('email', newLead.email).single();
            
            if (!existing) {
                const { error } = await supabase.from('leads').insert([newLead]);
                if (!error) {
                    console.log(`🎯 SUCCESS: Added ${newLead.full_name} (${newLead.email})`);
                    addedCount++;
                }
            }
        }

        console.log(`\n🎉 DONE! Injected ${addedCount} real verified founders into your CRM.`);
    } catch (error) {
        console.error("❌ Apollo API Error:", error.response?.data || error.message);
    }
}

generateApolloLeads();
